grafana:
  enabled: true
  adminPassword: "admin123"

prometheus:
  prometheusSpec:
    resources:
      requests:
        memory: 400Mi

alertmanager:
  enabled: false

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
